# Configuration for project
logging:
  level:
    org.springframework.security: DEBUG
    com.web: DEBUG
spring:
  datasource:
    url: jdbc:mysql://localhost:3306 # TODO Dev config. Make production
    username: root
    password: password
    driver-class-name: org.mariadb.jdbc.Driver