logging:
  level:
    org.springframework.security: DEBUG
    com.multiheaded.webapp: DEBUG
    org.hibernate.SQL: DEBUG
spring:
  jpa:
    database: default
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MariaDBDialect
  data:
    rest:
      base-path: /api
  main:
    datasource:
      platform: mariadb
      url: jdbc:mysql://localhost:3306/main?serverTimezone=UTC
      username: root
      password: password
      driver-class-name: org.mariadb.jdbc.Driver
  instagram:
    datasource:
      platform: mariadb
      url: jdbc:mysql://localhost:3306/instagram?serverTimezone=UTC
      username: root
      password: password
      driver-class-name: org.mariadb.jdbc.Driver
jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: UTC
