# Configuration for project
logging:
  level:
    org.springframework.security: DEBUG
    com.web: DEBUG
spring:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MariaDBDialect
  data:
    rest:
      base-path: /api
  datasource:
    platform: mariadb
    url: jdbc:mysql://localhost:3306/instagram # TODO Dev config. Make production
    username: root
    password: password
    driver-class-name: org.mariadb.jdbc.Driver
